### ISSUE TITLE
Documentation missing for Laravel setup?How can I use it in Larvel?

### ISSUE THREAD

**Issue by prashantidealittechno** [thephpleague/glide-laravel#2]
I just run the command to install as given, Now how to make the config file, I do not find any command to publish vendor to publish configuration file in config folder?
anybody know how to run this in Laravel 5.3?
Thanks

**Comment by reinink** [comment]
Sorry, I really need to add some better documentation to the website for Laravel. You don't need to create a config folder file or publish anything. You basically just wire it up manually. It really doesn't take that much.

I normally just manually add a service provider for Glide, and return a configured Glide server. Then create a route for Glide, injecting the configured Glide server from the Laravel IoC container. See the simple example to get an idea of how to do this: http://glide.thephpleague.com/1.0/simple-example/

I did create a screencast for version 0.3, which you can watch here: https://vimeo.com/118089742. This shows you how to get going in Laravel. However, do note that things have changed a bit since version 1.0, so view the documentation for how to setup the newer version.

Good luck! 😎

**Comment by prashantidealittechno** [comment]
Thank you for your precious time, It is very helpful.
